# All lengths in millimeters, all angles in degrees

# All keys inherit `global`
global:
  # Manufacturing tolerance (sliding)
  tol: 0.5
  # Manufacturing tolerance (friction-fit)
  tol_tight: 0.5
  # Wall thickness
  wall: 1.2
  # Rounding radius for inside edges (temperamental!)
#  inner_rad: 0.2
  inner_rad: 0.0

  # Key height
  key_h: 18.0
  # Key corner radius
  key_r: 4.0
  # Slope angles
  back_slope: 5.0
  front_slope: 10.0
  side_slope: 10.0
  # Curving magnitudes
  back_curve: 1.0
  front_curve: 1.0

# Each key must choose a `base`
bases:
  R1:
    front_dy: 10.1
    back_dy: 7.9
  R2:
    front_dy: 9.3
    back_dy: 8.0
  R3:
    front_dy: 9.3
    back_dy: 9.0
  R4:
    front_dy: 10.8
    back_dy: 11.4

# Keys can also give a list of `modifiers`
modifiers:
  convex:
    back_curve: -1.0
    front_curve: -1.0
